
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.comviva.asa.orchestrator2pulsar.ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-08-07T12:27:47.518-03:00
 * Generated source version: 3.3.4
 *
 */

@javax.jws.WebService(
                      serviceName = "PulsarInterfaceService",
                      portName = "PulsarInterfacePort",
                      targetNamespace = "http://ws.orchestrator2pulsar.asa.comviva.com/",
                      wsdlLocation = "file:/C:/Users/tbel/Documents/workspace_new/ASA_recordPendingTask/WebContent/wsPulsar.wsdl",
                      endpointInterface = "main.java.com.comviva.asa.orchestrator2pulsar.ws.PulsarInterface")

public class PulsarInterfacePortImpl implements PulsarInterface {

    private static final Logger LOG = Logger.getLogger(PulsarInterfacePortImpl.class.getName());

    /* (non-Javadoc)
     * @see main.java.com.comviva.asa.orchestrator2pulsar.ws.PulsarInterface#sendMessage(main.java.com.comviva.asa.orchestrator2pulsar.ws.MessageData arg0, java.lang.String arg1)*
     */
    public com.comviva.asa.orchestrator2pulsar.ws.RequestResponse sendMessage(com.comviva.asa.orchestrator2pulsar.ws.MessageData arg0, java.lang.String arg1) {
        LOG.info("Executing operation sendMessage");
        System.out.println(arg0);
        System.out.println(arg1);
        try {
            com.comviva.asa.orchestrator2pulsar.ws.RequestResponse _return = new com.comviva.asa.orchestrator2pulsar.ws.RequestResponse();
            _return.setMessageId("MessageId-1659622990");
            _return.setResultCode("ResultCode-397145726");
            _return.setResultDescription("ResultDescription2131118913");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
