package com.comviva.asa.orchestrator2pulsar.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.4
 * 2020-08-07T12:27:47.631-03:00
 * Generated source version: 3.3.4
 *
 */
@WebService(targetNamespace = "http://ws.orchestrator2pulsar.asa.comviva.com/", name = "PulsarInterface")
@XmlSeeAlso({ObjectFactory.class})
public interface PulsarInterface {

    @WebMethod
    @Action(input = "http://ws.orchestrator2pulsar.asa.comviva.com/PulsarInterface/sendMessageRequest", output = "http://ws.orchestrator2pulsar.asa.comviva.com/PulsarInterface/sendMessageResponse")
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://ws.orchestrator2pulsar.asa.comviva.com/", className = "com.comviva.asa.orchestrator2pulsar.ws.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://ws.orchestrator2pulsar.asa.comviva.com/", className = "com.comviva.asa.orchestrator2pulsar.ws.SendMessageResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.comviva.asa.orchestrator2pulsar.ws.RequestResponse sendMessage(

        @WebParam(name = "arg0", targetNamespace = "")
        com.comviva.asa.orchestrator2pulsar.ws.MessageData arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );
}
